### ISSUE TITLE
Failed to load the quippet package

### ISSUE THREAD

**Issue by fabriciosomini** [Azeirah/quippet#11]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 1.1.0
**System**: Unknown Windows Version
**Thrown From**: [quippet](https://github.com/Azeirah/quippet) package, v2.0.0
### Stack Trace

Failed to load the quippet package

```
At Cannot find module 'C:\Users\u6033450\AppData\Local\atom\app-1.1.0\resources\app.asar\node_modules\snippets'

Error: Cannot find module 'C:\Users\u6033450\AppData\Local\atom\app-1.1.0\resources\app.asar\node_modules\snippets'
    at Module._resolveFilename (module.js:334:15)
    at Function.Module._resolveFilename (C:\Users\u6033450\AppData\Local\atom\app-1.1.0\resources\app.asar\src\module-cache.js:383:52)
    at Function.Module._load (module.js:284:25)
    at Module.require (module.js:363:17)
    at require (module.js:382:17)
    at Object.<anonymous> (file:///C:/Users/u6033450/.atom/packages/quippet/lib/quippet-view.coffee:3:12)
    at Object.<anonymous> (file:///C:/Users/u6033450/.atom/packages/quippet/lib/quippet-view.coffee:1:1)
    at Module._compile (module.js:428:26)
    at Object.defineProperty.value [as .coffee] (C:\Users\u6033450\AppData\Local\atom\app-1.1.0\resources\app.asar\src\compile-cache.js:169:21)
    at Module.load (module.js:353:32)
```
### Commands

```
```
### Config

``` json
{
  "core": {
    "themes": [
      "one-dark-ui",
      "batman-syntax"
    ],
    "disabledPackages": [
      "javascript-snippets",
      "javascript-snippets",
      "javascript-snippets",
      "javascript-snippets",
      "javascript-snippets",
      "javascript-snippets"
    ]
  }
}
```
### Installed Packages

``` coffee
# User
auto-detect-indentation, v0.4.2
batman-syntax, v1.0.1
linter, v1.10.0
quippet, v2.0.0

# Dev
No dev packages
```

**Comment by fabriciosomini** [comment]
I got this error, do you know why?

**Comment by wochap** [comment]
i have the same problem, did you solve it?

**Comment by fabriciosomini** [comment]
No @wochap, I didn't :(

**Comment by Azeirah** [comment]
Sorry guys, this plugin was made before Atom made large changes to their api. Since I do not use Atom, I do not intend to maintain this plugin whatsoever. If you want to, you can try to fix the issues yourself, it shouldn't be too hard.

@fabriciosomini @wochap

**Comment by end-user** [comment]
Then please mark your project deprecated.
